.model small
.stack 550
.data 
    TOTAL_PRICE_WHOLENUM        DW 5678
    TOTAL_PRICE_FLOAT           DW 00050

    FIVE_PERCENT_WHOLENUM       DW 0
    FIVE_PERCENT_FLOAT_1        DW 0 ;FIRST TWO DECIMAL POINT
    FIVE_PERCENT_FLOAT_2        DW 0 ;THIRD & FOURTH DECIMAL POINT

.code
;TO DO > 1. PRINT THE NUMBERS
;        2. USE MACRO TO PRINT WHOLENUM & FLOAT SEPARATELY (?)
main PROC
    MOV AX,@DATA
    MOV DS,AX   

    ;CALC_5PERCENT PRICE

    XOR DX,DX

    MOV AX,TOTAL_PRICE_WHOLENUM
    MOV BX,100
    DIV BX

    PUSH DX

    MOV BX,5
    MUL BX

    POP DX
    PUSH AX

    MOV AX,DX
    MOV BX,5
    MUL BX

    XOR DX,DX

    MOV BX,100
    DIV BX

    POP BX
    PUSH DX

    ADD AX,BX
    MOV FIVE_PERCENT_WHOLENUM,AX

    ;FLOAT CALCULATION
    XOR DX,DX

    MOV AX,TOTAL_PRICE_FLOAT
    MOV BX,5
    MUL BX  

    MOV BX,100
    DIV BX

    XOR BX,BX
    POP BX
    ADD AX,BX

    MOV FIVE_PERCENT_FLOAT_1,AX
    MOV FIVE_PERCENT_FLOAT_2,DX

    XOR DX,DX
    MOV AX,FIVE_PERCENT_FLOAT_2
    MOV BX,10
    DIV BX

    CMP AX,5
    JL NO_ROUND_UP
    
    MOV AX,FIVE_PERCENT_FLOAT_1
    INC AX
    MOV FIVE_PERCENT_FLOAT_1,AX

NO_ROUND_UP:
    XOR DX,DX
    MOV AX,FIVE_PERCENT_WHOLENUM
    MOV BX,100
    DIV BX

    CMP AX,0
    JNE PRINT_HUNDREDS

    MOV AX,DX
    XOR DX,DX
    MOV BX,10
    DIV BX

    CMP AX,0
    JNE PRINT_TENS

PRINT_HUNDREDS:
    PUSH DX

    MOV AH,02H
    MOV DL,AL
    ADD DL,30H
    INT 21H

    POP DX

    MOV AX,DX
    XOR DX,DX
    MOV BX,10
    DIV BX

PRINT_TENS:
    PUSH DX

    MOV AH,02H
    MOV DL,AL
    ADD DL,30H
    INT 21H

    POP DX

    MOV AH,02H
    ADD DL,30H
    INT 21H

;PRINT DECIMAL POINT
    MOV AH,02H
    MOV DL,'.'
    INT 21H

    XOR DX,DX
    MOV AX,FIVE_PERCENT_FLOAT_1
    MOV BX,10
    DIV BX

    PUSH DX

    MOV AH,02H
    MOV DL,AL
    ADD DL,30H
    INT 21H

    POP DX

    MOV AH,02H
    ADD DL,30H
    INT 21H

    MOV AX,4C00H
    INT 21H
main ENDP
    END MAIN